export const BRIDAL_FAIR = [
  {
    id: 1,
    title: "【新型コロナウイルス感染症対策】",
    src: "/images/bridal_fair/bridal_fair_1.jpg",
    categories: [
      {
        selected: false,
        src: "/images/icon_fair_new.svg",
        label: "初めての見学",
        slug: "new",
      },
      {
        selected: false,
        src: "/images/icon_fair_food.svg",
        label: "試食会つき",
        slug: "food",
      },
      {
        selected: false,
        src: "/images/icon_fair_season.svg",
        label: "季節・期間限定",
        slug: "season",
      },
      {
        selected: false,
        src: "/images/icon_fair_ceremony.svg",
        label: "挙式体験",
        slug: "ceremony",
      },
      {
        selected: true,
        src: "/images/icon_fair_dress.svg",
        label: "ドレス試着",
        slug: "dress",
      },
      {
        selected: false,
        src: "/images/icon_fair_weekends.svg",
        label: "土日祝開催",
        slug: "weekends",
      },
      {
        selected: true,
        src: "/images/icon_fair_weekdays.svg",
        label: "平日限定開催",
        slug: "weekdays",
      },
      {
        selected: false,
        src: "/images/icon_fair_online.svg",
        label: "オンライン相談会",
        slug: "online",
      },
    ],
    events: [{ date: "2023-05-01" }, { date: "2023-05-02" }],
  },
  {
    id: 2,
    title: "【春のウェディングフェア】",
    src: "/images/bridal_fair/bridal_fair_2.jpg",
    categories: [
      {
        selected: false,
        src: "/images/icon_fair_new.svg",
        label: "初めての見学",
        slug: "new",
      },
      {
        selected: false,
        src: "/images/icon_fair_food.svg",
        label: "試食会つき",
        slug: "food",
      },
      {
        selected: false,
        src: "/images/icon_fair_season.svg",
        label: "季節・期間限定",
        slug: "season",
      },
      {
        selected: false,
        src: "/images/icon_fair_ceremony.svg",
        label: "挙式体験",
        slug: "ceremony",
      },
      {
        selected: true,
        src: "/images/icon_fair_dress.svg",
        label: "ドレス試着",
        slug: "dress",
      },
      {
        selected: false,
        src: "/images/icon_fair_weekends.svg",
        label: "土日祝開催",
        slug: "weekends",
      },
      {
        selected: true,
        src: "/images/icon_fair_weekdays.svg",
        label: "平日限定開催",
        slug: "weekdays",
      },
      {
        selected: true,
        src: "/images/icon_fair_online.svg",
        label: "オンライン相談会",
        slug: "online",
      },
    ],
    events: [{ date: "2023-05-03" }, { date: "2023-05-04" }],
  },
  {
    id: 3,
    title: "【オンライン見学会】",
    src: "/images/bridal_fair/bridal_fair_3.jpg",
    categories: [
      {
        selected: true,
        src: "/images/icon_fair_new.svg",
        label: "初めての見学",
        slug: "new",
      },
      {
        selected: false,
        src: "/images/icon_fair_food.svg",
        label: "試食会つき",
        slug: "food",
      },
      {
        selected: false,
        src: "/images/icon_fair_season.svg",
        label: "季節・期間限定",
        slug: "season",
      },
      {
        selected: false,
        src: "/images/icon_fair_ceremony.svg",
        label: "挙式体験",
        slug: "ceremony",
      },
      {
        selected: true,
        src: "/images/icon_fair_dress.svg",
        label: "ドレス試着",
        slug: "dress",
      },
      {
        selected: false,
        src: "/images/icon_fair_weekends.svg",
        label: "土日祝開催",
        slug: "weekends",
      },
      {
        selected: true,
        src: "/images/icon_fair_weekdays.svg",
        label: "平日限定開催",
        slug: "weekdays",
      },
      {
        selected: true,
        src: "/images/icon_fair_online.svg",
        label: "オンライン相談会",
        slug: "online",
      },
    ],
    events: [{ date: "2023-05-05" }, { date: "2023-05-06" }],
  },
  {
    id: 4,
    title: "【フードフェスティバル】",
    src: "/images/bridal_fair/bridal_fair_4.jpg",
    categories: [
      {
        selected: true,
        src: "/images/icon_fair_new.svg",
        label: "初めての見学",
        slug: "new",
      },
      {
        selected: false,
        src: "/images/icon_fair_food.svg",
        label: "試食会つき",
        slug: "food",
      },
      {
        selected: false,
        src: "/images/icon_fair_season.svg",
        label: "季節・期間限定",
        slug: "season",
      },
      {
        selected: false,
        src: "/images/icon_fair_ceremony.svg",
        label: "挙式体験",
        slug: "ceremony",
      },
      {
        selected: true,
        src: "/images/icon_fair_dress.svg",
        label: "ドレス試着",
        slug: "dress",
      },
      {
        selected: false,
        src: "/images/icon_fair_weekends.svg",
        label: "土日祝開催",
        slug: "weekends",
      },
      {
        selected: true,
        src: "/images/icon_fair_weekdays.svg",
        label: "平日限定開催",
        slug: "weekdays",
      },
      {
        selected: true,
        src: "/images/icon_fair_online.svg",
        label: "オンライン相談会",
        slug: "online",
      },
    ],
    events: [{ date: "2023-05-07" }, { date: "2023-05-08" }, { date: "2023-06-03" }],
  },
  {
    id: 5,
    title: "【ドレス試着会】",
    src: "/images/bridal_fair/bridal_fair_5.jpg",
    categories: [
      {
        selected: false,
        src: "/images/icon_fair_new.svg",
        label: "初めての見学",
        slug: "new",
      },
      {
        selected: false,
        src: "/images/icon_fair_food.svg",
        label: "試食会つき",
        slug: "food",
      },
      {
        selected: false,
        src: "/images/icon_fair_season.svg",
        label: "季節・期間限定",
        slug: "season",
      },
      {
        selected: false,
        src: "/images/icon_fair_ceremony.svg",
        label: "挙式体験",
        slug: "ceremony",
      },
      {
        selected: false,
        src: "/images/icon_fair_dress.svg",
        label: "ドレス試着",
        slug: "dress",
      },
      {
        selected: false,
        src: "/images/icon_fair_weekends.svg",
        label: "土日祝開催",
        slug: "weekends",
      },
      {
        selected: true,
        src: "/images/icon_fair_weekdays.svg",
        label: "平日限定開催",
        slug: "weekdays",
      },
      {
        selected: false,
        src: "/images/icon_fair_online.svg",
        label: "オンライン相談会",
        slug: "online",
      },
    ],
    events: [{ date: "2023-05-09" }, { date: "2023-05-10" }],
  },
];

export const CATEGORIES = [
  {
    selected: true,
    src: "/images/icon_fair_new.svg",
    label: "初めての見学",
    slug: "new",
  },
  {
    selected: true,
    src: "/images/icon_fair_food.svg",
    label: "試食会つき",
    slug: "food",
  },
  {
    selected: true,
    src: "/images/icon_fair_season.svg",
    label: "季節・期間限定",
    slug: "season",
  },
  {
    selected: true,
    src: "/images/icon_fair_ceremony.svg",
    label: "挙式体験",
    slug: "ceremony",
  },
  {
    selected: true,
    src: "/images/icon_fair_dress.svg",
    label: "ドレス試着",
    slug: "dress",
  },
  {
    selected: true,
    src: "/images/icon_fair_weekends.svg",
    label: "土日祝開催",
    slug: "weekends",
  },
  {
    selected: true,
    src: "/images/icon_fair_weekdays.svg",
    label: "平日限定開催",
    slug: "weekdays",
  },
  {
    selected: true,
    src: "/images/icon_fair_online.svg",
    label: "オンライン相談会",
    slug: "online",
  },
];
